---
# tasks file for roles/nginx
    - name: Install apt 
      apt:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
        update_cache: yes
        state: present
        

    - name: delete default config NGINX 
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent


    - name: Create config nginx for reverse proxy 
      template:
        # src: nginx_site.conf.j2
        src: "{{ item.template | default('nginx_site.conf.j2') }}"
        dest: "/etc/nginx/sites-available/{{ item.domain_name }}"
        mode: '0644'
      loop: "{{ nginx_sites }}"

    - name: Activate 
      file:
        src: "/etc/nginx/sites-available/{{ item.domain_name }}"
        dest: "/etc/nginx/sites-enabled/{{ item.domain_name }}"
        state: link
        force: true
      loop: "{{ nginx_sites }}"

    - name: check conf NGINX
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0

    - name: Restart  NGINX
      service:
        name: nginx
        state: restarted
        enabled: true


