# Vagrant.configure("2") do |config|
#   config.vm.box = "debian/bookworm64"
#   config.vm.hostname = "gno-validator"

#   config.vm.provider "virtualbox" do |vb|
#     vb.name = "Debian12VM"
#     vb.memory = "1024"
#     vb.cpus = 2
#   end


#   # activate  SSH root
#   config.vm.provision "shell", inline: <<-SHELL
#     echo "Activation du login root en SSH..."
#     sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
#     mkdir -p /root/.ssh
#     cp /home/vagrant/.ssh/authorized_keys /root/.ssh/authorized_keys
#     chown root:root /root/.ssh/authorized_keys
#     chmod 600 /root/.ssh/authorized_keys
#     systemctl restart ssh
#   SHELL


# end

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # Validator node
  config.vm.define "validator" do |v|
    v.vm.hostname = "gno-validator-test"
    v.vm.network "private_network", ip: "192.168.56.10"
    v.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 1
      vb.name = "gno-validator-test"
    end
  end

  # Sentry node
  config.vm.define "sentry" do |s|
    s.vm.hostname = "gno-sentry-test"
    s.vm.network "private_network", ip: "192.168.56.11"
    s.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
      vb.name = "gno-sentry-test"
    end
  end

  # Monitoring node
  config.vm.define "monitoring" do |m|
    m.vm.hostname = "gno-monitoring-test"
    m.vm.network "private_network", ip: "192.168.56.12"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
      vb.name = "gno-monitoring-test"
    end
  end

  # Common provisioning: install Python for Ansible + enable root SSH
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -q
    apt-get install -y -q python3 python3-pip
    sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
    mkdir -p /root/.ssh
    cp /home/vagrant/.ssh/authorized_keys /root/.ssh/authorized_keys
    chown root:root /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
    systemctl restart ssh
  SHELL
end