Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "gno-validator"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Debian12VM"
    vb.memory = "1024"
    vb.cpus = 2
  end


  # activate  SSH root
  config.vm.provision "shell", inline: <<-SHELL
    echo "Activation du login root en SSH..."
    sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
    mkdir -p /root/.ssh
    cp /home/vagrant/.ssh/authorized_keys /root/.ssh/authorized_keys
    chown root:root /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
    systemctl restart ssh
  SHELL


end